Gemfile
Gemfile.lock
_plugins/common.rb
import_language.rb

Allow to import from Lokalise the translations of pages other than the index.
It still doesn't support translating those pages titles, but we're going that way.

Translate other pages

---

import_language.rb

The `strings.yml` is used to generate the SVGs for each language, so now we import them from Lokalise.

Import strings.yml from lokalise

---

about-en.md

All the other links were contained within parentheses, so Lange's should too.

Lange's link follows conventional paren wrapping

---

contact-en.md

The original link did not lead anywhere. The other option would be to simply refer to /contribute page on the site itself which has variety of options how people can contribute.

Fix the link in contacts

---

_sections/act_and_prepare/en/02-do/17-monitor-symptoms.md

Tables need to be wrapped in a `.table-wrap` div to prevent them from causing horizontal scrolling when they are wider than the page.
**BEFORE:**
**AFTER:**

Fixed table breaking layout on small screens

---

_includes/doc-top.html
_includes/lang-bar.html
_layouts/default.html
_layouts/home.html
index-cs.md
index-de.md
index-el.md
index-en.md
index-es.md
index-fr.md
index-it.md
index-ru.md
index.md

Closes #284 
This was originally reported as an issue with Greek, but it turns out this was actually an issue for all the languages besides English. Thanks to good research by @mpitid the root cause was that the hompage layout was not set up in a way that the `lang` attribute was being set correctly.
This should be reviewed by someone familiar with the localization infrastructure before merging...

Fix language attribute on homepage

---

_scripts/import_resources.py

Few improvements to the resource import process.
1. use yaml.dump to properly escape the attributes for each resource
2. use lowercase url so that it is consistent with the column name and doesn't need special treatment (subsequent change to resources.md and regen of existing resource will be part of a separate PR)
3. Added --clobber flag that skips over already existing resource files by default

Resource script improvements

---

_resources/2020-03-21-safe-handling-and-decontamination.md
_resources/2020-03-22-covid-tracking-project.md
_resources/2020-03-22-official-covid-19-nj-info-hub.md
_resources/2020-03-23-covid-19-collective-care.md
_resources/2020-03-23-covid-19-resources-for-students.md
_resources/2020-03-23-covid-19-tracking-and-projections.md
_resources/2020-03-23-loss-of-sense-of-smell-as-marker-of.md
_resources/2020-03-23-us-covid-19-mutual-aid-resources.md
_resources/2020-03-24-covid-19-open-source-helpdesk.md
_resources/2020-03-24-data-against-covid-19.md
_resources/2020-03-25-corona-virus-full-fact-news-checkin.md
_resources/2020-03-27-coronavirus-the-science-explained.md
_resources/2020-03-27-covid-19-research-search-engine.md
_resources/2020-03-27-why-you-must-act-now-by-state.md
_resources/2020-03-28-covid-19-spread-vs-healthcare-capac.md
_resources/2020-03-28-covid19-day-by-day.md
_resources/2020-03-28-epidemic-calculator.md
_resources/2020-03-28-ministerio-de-salud-de-la-nacin.md
_resources/2020-03-28-world-health-organization.md
_resources/2020-03-29-coronavirus-disease-covid-19-statis.md
_resources/2020-04-03-brief-video-explaining-why-flatteni.md
_resources/2020-04-03-co-mask.md
_resources/2020-04-03-coronavirus-the-science-explained.md
_resources/2020-04-03-makermask.md
_resources/2020-04-03-the-covid-tracking-project.md
_resources/2020-04-03-where-to-safely-shop-during-covid-1.md
_scripts/import_resources.py
resources.md

This is a second part of https://github.com/flattenthecurve/guide/pull/305 (should be only integrated once the other PR is in).
This PR:
1. switches to lowercase url attribute for resources (to eliminate need for special treatments)
2. properly escapes all resource attributes & removes some ad-hoc empty lines in the resource files
3. Converts United States to USA in one of the resource files. [1]
[1] it might be worth creating automatic rule converting the country name to the canonical form when new resource submission is received.

Fixes to the resource page

---

_layouts/legacy-home.html
_resources/2020-04-03-where-to-safely-shop-during-covid-1.md
_sass/minima.scss
_sass/minima/_base.scss
_sass/minima/_layout.scss
_sass/minima/_legacy-homepage.scss
index-cs.md
index-de.md
index-el.md
index-es.md
index-fr.md
index-it.md
index-ru.md
resources.md

The Resources page was looking really cluttered...
* Cleaned up the template
* Cleaned up the CSS
* Re-implemented a hack for the legacy homepage (that was applying globally to the whole site)
* Fixed a resource that had "United States" instead of "USA"

Prettier resources

---

_resources/2020-03-21-safe-handling-and-decontamination.md
_resources/2020-03-22-covid-tracking-project.md
_resources/2020-03-22-official-covid-19-nj-info-hub.md
_resources/2020-03-23-covid-19-collective-care.md
_resources/2020-03-23-covid-19-resources-for-students.md
_resources/2020-03-23-covid-19-tracking-and-projections.md
_resources/2020-03-23-loss-of-sense-of-smell-as-marker-of.md
_resources/2020-03-23-us-covid-19-mutual-aid-resources.md
_resources/2020-03-24-covid-19-open-source-helpdesk.md
_resources/2020-03-24-data-against-covid-19.md
_resources/2020-03-25-corona-virus-full-fact-news-checkin.md
_resources/2020-03-27-coronavirus-the-science-explained.md
_resources/2020-03-27-covid-19-research-search-engine.md
_resources/2020-03-27-why-you-must-act-now-by-state.md
_resources/2020-03-28-covid-19-spread-vs-healthcare-capac.md
_resources/2020-03-28-covid19-day-by-day.md
_resources/2020-03-28-epidemic-calculator.md
_resources/2020-03-28-ministerio-de-salud-de-la-nacin.md
_resources/2020-03-28-world-health-organization.md
_resources/2020-03-29-coronavirus-disease-covid-19-statis.md
_resources/2020-04-03-brief-video-explaining-why-flatteni.md
_resources/2020-04-03-co-mask.md
_resources/2020-04-03-coronavirus-the-science-explained.md
_resources/2020-04-03-makermask.md
_resources/2020-04-03-the-covid-tracking-project.md
_resources/2020-04-03-where-to-safely-shop-during-covid-1.md
resources.md

I guess I now know why URL in resource attributes was uppercase. Turns out that resource.url contains location of the underlying md file and can't be populated by the file contents. I have switched to use target instead. This should fix the links. 
Changes to the spreadsheet and resource_import.py will follow.

Fix resource hrefs by replacing url with target

---

_scripts/import_resources.py

Second part of https://github.com/flattenthecurve/guide/issues/312. Fixes resource automation script. The underlying spreadsheet has already been converted to use target column name.

Fix import_resources.py to use target instead of url

---

_includes/header.html

Fixes duplicate home link in nav

---

_data/en/strings.yml
_includes/pending-sci-review.html
_sass/minima/_act_prepare.scss

This work is derived from a prototype by @kendrahavens. The placement of the notice, text and the styling is theirs. I have incorporated feedback from @matiasgarciaisaia about how to deal with string translations.
This consist of:
1. pending-sci-review string that should be soon translated into all target languages
2. _include/pending-sci-review.html notice that can be included in md files. Notice will only show up if the content has been translated into the current language.
3. css style for the notice
I'm working on modifications to the `import_language.rb` script that will insert the disclaimer notices into files when it detects that they have not been scientifically reviewed.

Disclaimer for missing scientific review

---

_scripts/compare_md_structure.py

This script allows comparing structural content (element tree) of the markdown files. This compares English (original) with the translated markdowns files, generates html and then produces diffs for any structural differences found.
Markdown files are transformed into html and parsed into element tree (using lxml). Documents are then traversed and turned into string representations /path/to/tag#attr1=value1#attr2=value2. Lists of these strings are then compared and diffed for each (english, translation) pair.
Flags for this script are:
1. --langs [de,fr,...], restrict analysis only for given translations
2. --include-regex, only analyze tags where the string representation matches given regex (e.g. "/h.#" to compare headers)
3. --exclude-regex, skip tags where string representation …

Md syntax compare

---

.pre-commit-config.yaml
_resources/2020-04-03-makermask.md
_scripts/pre-commit-warn-on-resources.sh

add pre-commit checks that will disallow manual modifications to _resources files and point people to the form. Unfortunately this will still need to be set-up by collaborators by installing pre-submit and activating on their local forks/clones by running this sequence:
```
pip install pre-commit
pre-commit install
```
I'm also working on a workflow that would send people to the form when they send PRs modifying _resources/ which might catch those that may not be caught by the pre-commit check.
It seems to me that pre-commit may be used for other Q&A tasks (e.g. limited markdown linting and such) so we might want to think if we would like to use them by default and create "set up your repo" instructions for collaborators that will ensure that pre-commit hooks are installed and used across …

Resource pre commit checks

---

import-translations.sh
import_language.rb

The core of this change is to allow inserting pending-sci-review notice to act_and_prepare articles. To allow for this, the structure of the language import script has been refactored so that this could be done relatively cleanly.
Here's the brief summary of the changes:
1. added --sci-review-notice flag which will trigger insertion of pending-sci-review notices for translations that are not marked as reviewed in Lokalise
2. Refactoring of the code that pulls translations from Lokalise. The code has been moved to a function which allows us to specify whether we want to retrieve translations or only reviewed keys. The code returns JSON instead of generating local files under `_translations/` and the method is called twice by default to find out which keys are not scientifically reviewed. …

Refactor import_languages.rb script and allow for optional pending-sci-review

---

.github/workflows/latest-translations.yml

Imports latest translations from Lokalise into latest-translation/$lang branch. For now, this is only run for CS and runs once per hour.

Add latest-translation workflow for CS.

---

_config.yml
import_language.rb

Mainly around pending-sci-review noticiations.
1. Script crashed for languages that did not have any keys in the reviewed state. This is now fixed.
2. I have consolidated indentation to be 2 spaces everywhere (cosmetic fix only).
3. Removed `--[no-]sci-review-notice` commandline flag and replaced with more flexible configuration block in the `_config.yml`. This allows us to fine tune where we want these notices to be shown.
4. Move the decision logic for whether the notice should be shown into its own function for better readability.
5. Do not show notices in the section header files in act_and_prepare (these were introduced in PR #336)

Few improvements to the language import script

---

.github/workflows/latest-translations.yml

actions/cache@v1 does not work for scheduled workflows and this seems to also break use of docker-compose.ci.yml. So get rid of both of these.
Also clean up the workflow naming.

Fix latest-translations workflow

---

import-translations.sh

While this solves the problem of root-owned files when the script is run locally it messes up things when this script is run from github actions. So I'm removing this.

Do not override user when running import-translations.sh
