flattenthecurve/guide

_content/en/04-about/04-contributing.md

fix typo in financially

---

_sass/minima.scss
_sass/minima/_layout.scss

Now links in navbar are white in desktop and black in mobile.
Fixes #22

Change nav link color in mobile

---

_content/en/01-context/03-site-intro-and-updates.md
_layouts/default.html
_layouts/home.html
_sass/_custom.scss
_sass/minima.scss

wip: additional commits will be added for better styling

TOC moved to the sidebar on desktop and bottom on mobile

---

.github/ISSUE_TEMPLATE/Localisation_Translation.md
.github/ISSUE_TEMPLATE/Website-bug-fix.md
.github/ISSUE_TEMPLATE/content.md
.github/ISSUE_TEMPLATE/legal-scientific-dispute.md
.github/ISSUE_TEMPLATE/website-feature-request.md

create issue templates

---

README.md

This is a very basic first step towards making it quicker/easier for a developer to get up and running on this project.
Closes #90 (for now)

Added developer section to docs

---

CODE_OF_CONDUCT.md

Issue reference: https://github.com/flattenthecurve/guide/issues/84
The "CODE_OF_CONDUCT" is a template and the source is referenced in it.
Feel free to update any part you think dosn't apply to this project or add anything you think is missing.

[Proposal] Adding CODE_OF_CONDUCT

---

_sass/minima/_layout.scss
_sections/act_and_prepare/en/03-dont/04-do-not-attend-non-essential-public-gatherings.md
_sections/act_and_prepare/en/03-dont/09-do-not-go-to-doctor-without-calling-ahead.md
_sections/home/en/01-context/07-it-is-here.md

Closes #8 
This PR only includes the updates for English (no additional translations).
~The table doesn't look great on narrow screens, but I'm going to submit a subsequent PR with that CSS so that this one isn't unnecessarily delayed.~ Updated with responsive table solution.

Replace text images with markdown

---

_sass/minima.scss

Add white space between DOs and DONTs

---

_sass/minima.scss
_sass/minima/_act_prepare.scss
_sass/minima/_base.scss
_sass/minima/_header.scss
_sass/minima/_home.scss
_sass/minima/_layout.scss
images/mortality-rate-by-age.svg

In relation to #186 and #104 
Added some spacing everywhere to make it more readable, as per discussed with @jkicillof

Fixed nav bar overlaping and added some minor styles changes

---

_sections/home/en/01-context/01-site-header.md

Doesn't look great on mobile now (depending on the device's width), but we can iterate that.

Re-add link to suscribe to mailing list

---

_content/en/03-dont/05-do-not-hoard-masks.md

This section was too vague, used questionable reasoning, and seemed unjustified.
> Do not hoard masks
The word "hoard" is doing a lot of work here, but is vague. What constitutes hoarding? What about buying one respirator for each member of the family? Is that hoarding? What if you buy 60 to wear on the way to work on the train, and you expect to use 1 per day and have to wear them for 2 months?
> Healthcare workers desperately need them to care for you and your loved ones.
This is certainly true, but whether you having your own mask means healthcare workers will have too few depends on the context. If your region has no shortage of masks, then you having your own does not impede healthcare workers from safely doing their job. At the very least, this should be highly qualified, since …

Remove mask-hoarding section

---

_sections/act_and_prepare/en/03-dont/05-do-not-hoard-masks.md

It was inadvertently undeleted.
See [this](https://github.com/flattenthecurve/guide/pull/131) merged PR for the discussion, including the two approvals.

Re-delete "Do not hoard masks" section

---

_sections/act_and_prepare/en/02-do/13-prepare-a-hot-zone.md

Once again, we have to differentiate between surgical masks (for which there is a shortage) and cloth masks which are not ringfenced (yet) for medical professionals.

more cloth mask work

---

_sections/act_and_prepare/en/02-do/03-lower-your-overall-risk.md

Minor changes to be up to date with current recommendations relating to social distancing

minor changes to be current

---

_sections/act_and_prepare/en/02-do/16-wear-a-mask-when-in-public.md

Pro **cloth** masks section if a person has to go into the public setting (including mass transport). 
https://www.youtube.com/watch?v=_JH04M04eQQ made a very strong case, pulling together evidence presented previously elsewhere

cloth masks

---

import_language.rb

This PR will make the preview workflow add any missing language that's getting built to the site's list of languages - so we don't have to manually add it in a new commit.
This involves re-writting the `_config.yml`, which can be a bit risky, but I tried to be careful - and we manually review & approve PRs before merging, so we should be good-ish.

Add missing languages to config.yml when importing

---

_sections/act_and_prepare/en/02-do/11-keep-your-home-clean.md

adds content from https://github.com/flattenthecurve/guide/issues/97 to the section 11, keep your home clean. 
Also dropping the note about this being currently written/developed set of guidelines. AFAIK same can be said about all content here and with the official CDC guidelines in place, this is already evolving in the right direction.

Add cdc guidelines for disinfection

---

_sections/act_and_prepare/en/02-do/03-lower-your-overall-risk.md
_sections/act_and_prepare/en/02-do/11-keep-your-home-clean.md

Replaced section talking about lowering overall risks with "Stay at home" recommendations. We are past the mild preventive measures and need aggressive action now.
https://github.com/flattenthecurve/guide/issues/127

Issue 127: Stay home

---

_sections/act_and_prepare/en/02-do/18-get-enough-vitamin-D.md

Closes [this](https://github.com/flattenthecurve/guide/issues/255) issue

Add "Get enough vitamin D" section

---

_scripts/import_resources.py

1. fixed encoding issues
2. strip trailing whitespace more aggressively
3. skip over rows that do not have approved_by column populated

Resource script improvements

---

_sections/act_and_prepare/en/02-do/16-wear-a-mask-when-in-public.md

Also, move each markdown sentence onto its own line for more readable GitHub diffing.

Add parenthetical to explain scientific jargon

---

_sections/act_and_prepare/en/03-dont/02-do-not-touch-your-face.md

This is not the most common way the virus enters the body according to the source.

Not the most common way

---

_sections/home/en/01-site-header.md

Changed "never" to "do not." Could change it to "do not touch your face with unwashed hands," as that poses the greatest risk of transmission.

Do not touch your face

---

_scripts/resource_notifications_app_script.js

This code runs on the Flatten The Curve - Resource Submission (Responses) sheet
and ensures that:
1. new resources are copied over to Approved Resources tab
2. notifications are sent to the #resources slack channel with instructions

Source code for the Google Apps Script.

---

_sections/act_and_prepare/en/02-do/16-wear-a-mask-when-in-public.md

Countries are beginning to implement masks or all when mixing in public policies now. Flattenthecurve should note that and track in.

Add list of countries liking and mandating "masks for all" when in publc

---

_sections/act_and_prepare/en/02-do/08-work-from-home.md

Closes [this](https://github.com/flattenthecurve/guide/issues/4) issue, since it includes more privacy-friendly options.

Update WFH collaboration tools

---

_config.yml

Add CS into supported/launched languages.

---

_sections/COVID-19/en/08-the-us-healthcare-system.md

- Remove claim that wasn't supported by the linked study
- Add link to the most recent report from the WHO
- Update phrasing for readability
- Put each sentence on its own line for better GitHub diffing
Closes [this](https://github.com/flattenthecurve/guide/issues/1) issue

Improve US healthcare system section

---

contribute-en.md

Page titles are H1s so headings should start with H2s and downward

Fixed duplicate H1 on Contribute page

---

_sass/minima/_base.scss
_sass/minima/_home.scss
_sections/home/en/01-site-header.md

Fixes the text alignment to match the original design...

Fixed text align on mobile homepage

---

_sections/home/en/01-site-header.md

Closes [this](https://github.com/flattenthecurve/guide/issues/276) issue
I'm not sure who should approve this kind of change, so please add them as a reviewer if _you_ know!

Main page subheading better explains core mission

---

_sections/act_and_prepare/en/02-do/07-stock-up-on-food-and-essentials.md

Embedding of tweets is also used in 03-dont/ sections and I think it improves readability of the information.

Embed tweet from Emma Hodcroft

---

_sections/COVID-19/en/05-this-is-not-normal-flu.md
_sections/COVID-19/en/07-it-is-here.md

Update Covid-19 to COVID-19

---

_scripts/import_resources.py

Add some content normalization:
1. (ensure that COVID-19 is always capitalized in the description)
2. Ensure that all US country names are mapped to USA
Turn off default_flow_style in the yaml dump so that output is consistent across platforms (our github action somehow has this on and my workstation has it off, so this is strange)

Resource import automation - minor improvements

---

_includes/disclaimer/cs/disclaimer.md
_includes/disclaimer/de/disclaimer.md
_includes/disclaimer/el/disclaimer.md
_includes/disclaimer/en/disclaimer.md
_includes/disclaimer/es/disclaimer.md
_includes/disclaimer/fr/disclaimer.md
_includes/disclaimer/it/disclaimer.md
_includes/disclaimer/mr/disclaimer.md
_includes/disclaimer/ru/disclaimer.md
_sass/minima/_act_prepare.scss

I'm working on auto-including the disclaimer into resources/md files that are marked as not reviewed.

Merge disclaimers into my experimental branch

---

_sections/act_and_prepare/en/04-myths/06-other-people.md

Washingtonpost article providing insight on the effectiveness of social distancing through graphic simulations.

Added link to Washingtonpost corona-simulator.

---

_resources/README.md

Discourage editing of these files by hand.
Covering all the bases for issue #361

Add README file to _resources/

---

add-resource.html

This creates www.flattenthecurve.com/add-resource which is easy to remember link to the resource submission form.

Add simple redirect page for the resource submission form.

---

LICENSE

Do not approve this until consensus is reached in #342. This closes #342 when merged.

Switch LICENCE to CC-BY 4.0

---

_scripts/git-push.sh

This adds all locally modified files, commits and then pushes
to the remote repository.
This is suitable to use in workflows that modify the codebase.
This is slight generalization of `_scrips/push-translations.sh`

Add generalized git-push.sh script.

---

.github/workflows/latest-translations.yml

1. Run this for CS, NL, SV languages
2. Use preview/latest/$LANG branch to see if it will automatically kick
off zeit previews.
3. Extract env variables to job level

Automatic translation integration

---

_sections/home/en/01-site-header.md

Closes https://github.com/flattenthecurve/guide/issues/386

Tweaked homepage "what to do" link

---

_config.yml

This is working. Enable it everywhere.

Enable pending-sci-review notices everywhere

---

import_language.rb

This adds sci-review notices to COVID-19 page as well. Closes #318

Add pending review notice to COVID-19 articles

---

_sections/act_and_prepare/en/06-myths/WHO-myth-buster-summary.md

I will keep update this content when there are substantial change in the WHO link.

WHO-myth-buster-summary.md
